### ISSUE TITLE
HTML Special characters

### ISSUE THREAD

**Issue by martoio** [Bashnet/prj-rev-bwfs-dasmoto#1]
Check out this article that explains why you need to care about using special characters in HTML: http://text-symbols.com/html/encode/

https://github.com/Bashnet/prj-rev-bwfs-dasmoto/blob/bb826ece1f7371925b82d9c2c9bf87bb81600faa/Dasmoto/index.html#L9

The ampersand should be written as:
``&amp;``

**Comment by Bashnet** [comment]
Thanks. I was wondering why the & sign was colored red in my code. i will look into the article
